name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "building nothing..."


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "tests required"
